***Imports***

In [1]:
import pandas as pd

Fundir os dados mensais

In [ ]:
from pathlib import Path
import pandas as pd

pasta = Path("Data")
arquivos = sorted(pasta.glob("T_ONTIME_REPORTING*.csv"))

if len(arquivos) != 24:
    raise ValueError(f"Esperava 24 arquivos, mas encontrei {len(arquivos)}.")

df_final = pd.concat(
    [pd.read_csv(arquivo) for arquivo in arquivos],
    ignore_index=True
)

df_final.to_csv(pasta / "T_ONTIME_REPORTING_completo.csv", index=False)

Carregar o dataset

In [2]:
df = pd.read_csv('Data/T_ONTIME_REPORTING_completo.csv')

## Resumo do dataframe

In [3]:
print(df.shape)

(13577024, 28)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13577024 entries, 0 to 13577023
Data columns (total 28 columns):
 #   Column                 Dtype
---  ------                 -----
 0   YEAR                   int64
 1   QUARTER                int64
 2   MONTH                  int64
 3   DAY_OF_MONTH           int64
 4   DAY_OF_WEEK            int64
 5   FL_DATE                object
 6   OP_UNIQUE_CARRIER      object
 7   ORIGIN_AIRPORT_ID      int64
 8   ORIGIN_AIRPORT_SEQ_ID  int64
 9   ORIGIN_CITY_MARKET_ID  int64
 10  ORIGIN_CITY_NAME       object
 11  DEST_AIRPORT_ID        int64
 12  DEST_AIRPORT_SEQ_ID    int64
 13  DEST_CITY_MARKET_ID    int64
 14  DEST_CITY_NAME         object
 15  CRS_DEP_TIME           int64
 16  DEP_TIME               float64
 17  DEP_DELAY              float64
 18  DEP_DELAY_NEW          float64
 19  DEP_DEL15              float64
 20  DEP_DELAY_GROUP        float64
 21  CRS_ARR_TIME           int64
 22  ARR_TIME               float64
 23  ARR_DELAY              float64
 24  ARR_DELAY_NEW          float64
 25  ARR_DEL15              float64
 26  CANCELLED              float64
 27  DIVERTED               float64
dtypes: float64(11), int64(13), object(4)
memory usage: 2.8+ GB

In [5]:
df.isnull().sum().sort_values(ascending=False)

ARR_DEL15                301609
ARR_DELAY_NEW            301609
ARR_DELAY                301609
ARR_TIME                 272574
DEP_DELAY_GROUP          261877
DEP_DEL15                261877
DEP_DELAY_NEW            261877
DEP_DELAY                261877
DEP_TIME                 261738
YEAR                          0
QUARTER                       0
CANCELLED                     0
CRS_ARR_TIME                  0
CRS_DEP_TIME                  0
DEST_CITY_NAME                0
DEST_CITY_MARKET_ID           0
DEST_AIRPORT_SEQ_ID           0
DEST_AIRPORT_ID               0
ORIGIN_CITY_NAME              0
ORIGIN_CITY_MARKET_ID         0
ORIGIN_AIRPORT_SEQ_ID         0
ORIGIN_AIRPORT_ID             0
OP_UNIQUE_CARRIER             0
FL_DATE                       0
DAY_OF_WEEK                   0
DAY_OF_MONTH                  0
MONTH                         0
DIVERTED                      0
dtype: int64

In [6]:
df.describe()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,...,DEP_DELAY_NEW,DEP_DEL15,DEP_DELAY_GROUP,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,CANCELLED,DIVERTED
count,1.357702e+07,1.357702e+07,1.357702e+07,1.357702e+07,1.357702e+07,1.357702e+07,1.357702e+07,1.357702e+07,1.357702e+07,1.357702e+07,...,1.331515e+07,1.331515e+07,1.331515e+07,1.357702e+07,1.330445e+07,1.327542e+07,1.327542e+07,1.327542e+07,1.357702e+07,1.357702e+07
mean,2.022504e+03,2.523969e+00,6.571264e+00,1.574770e+01,3.982595e+00,1.265333e+04,1.265336e+06,3.174007e+04,1.265333e+04,1.265337e+06,...,1.544240e+01,2.092865e-01,1.644509e-01,1.487385e+03,1.458779e+03,6.828148e+00,1.523260e+01,2.081665e-01,1.982975e-02,2.384764e-03
std,4.999809e-01,1.107237e+00,3.406965e+00,8.779758e+00,2.001932e+00,1.528548e+03,1.528546e+05,1.313179e+03,1.528553e+03,1.528551e+05,...,5.297082e+01,4.067993e-01,2.297921e+00,5.234886e+02,5.475199e+02,5.575449e+01,5.255027e+01,4.059966e-01,1.394150e-01,4.877579e-02
min,2.022000e+03,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.013500e+04,1.013506e+06,3.007000e+04,1.013500e+04,1.013506e+06,...,0.000000e+00,0.000000e+00,-2.000000e+00,1.000000e+00,1.000000e+00,-1.190000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.022000e+03,2.000000e+00,4.000000e+00,8.000000e+00,2.000000e+00,1.129200e+04,1.129202e+06,3.064700e+04,1.129200e+04,1.129202e+06,...,0.000000e+00,0.000000e+00,-1.000000e+00,1.100000e+03,1.043000e+03,-1.500000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.023000e+03,3.000000e+00,7.000000e+00,1.600000e+01,4.000000e+00,1.288900e+04,1.288903e+06,3.145300e+04,1.288900e+04,1.288903e+06,...,0.000000e+00,0.000000e+00,-1.000000e+00,1.515000e+03,1.501000e+03,-6.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2.023000e+03,4.000000e+00,1.000000e+01,2.300000e+01,6.000000e+00,1.402700e+04,1.402702e+06,3.246700e+04,1.402700e+04,1.402702e+06,...,1.000000e+01,0.000000e+00,0.000000e+00,1.925000e+03,1.918000e+03,1.000000e+01,1.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00
max,2.023000e+03,4.000000e+00,1.200000e+01,3.100000e+01,7.000000e+00,1.686900e+04,1.686902e+06,3.610100e+04,1.686900e+04,1.686902e+06,...,4.413000e+03,1.000000e+00,1.200000e+01,2.400000e+03,2.400000e+03,4.405000e+03,4.405000e+03,1.000000e+00,1.000000e+00,1.000000e+00

### Análise das colunas

In [7]:
df['QUARTER'].value_counts()

QUARTER
3    3516452
2    3431265
4    3408931
1    3220376
Name: count, dtype: int64

In [8]:
df['YEAR'].value_counts()

YEAR
2023    6847899
2022    6729125
Name: count, dtype: int64

In [16]:
df['DAY_OF_MONTH'].value_counts()

DAY_OF_MONTH
27    455806
20    454053
21    453396
17    453106
10    452055
13    450914
26    450180
22    450136
14    449138
28    448055
6     446940
18    446843
16    446692
11    446569
19    446529
7     445422
9     445312
12    444879
15    444860
2     444283
3     443722
23    443491
8     442710
25    441033
1     440652
5     440467
24    438634
4     437493
30    409988
29    407504
31    256162
Name: count, dtype: int64

In [17]:
df['DAY_OF_WEEK'].value_counts()

DAY_OF_WEEK
5    2020151
1    2009187
4    2007521
7    1979637
3    1914825
2    1886099
6    1759604
Name: count, dtype: int64

In [20]:
df['FL_DATE'].tail(50)

13576974    12/31/2023 12:00:00 AM
13576975    12/31/2023 12:00:00 AM
13576976    12/31/2023 12:00:00 AM
13576977    12/31/2023 12:00:00 AM
13576978    12/31/2023 12:00:00 AM
13576979    12/31/2023 12:00:00 AM
13576980    12/31/2023 12:00:00 AM
13576981    12/31/2023 12:00:00 AM
13576982    12/31/2023 12:00:00 AM
13576983    12/31/2023 12:00:00 AM
13576984    12/31/2023 12:00:00 AM
13576985    12/31/2023 12:00:00 AM
13576986    12/31/2023 12:00:00 AM
13576987    12/31/2023 12:00:00 AM
13576988    12/31/2023 12:00:00 AM
13576989    12/31/2023 12:00:00 AM
13576990    12/31/2023 12:00:00 AM
13576991    12/31/2023 12:00:00 AM
13576992    12/31/2023 12:00:00 AM
13576993    12/31/2023 12:00:00 AM
13576994    12/31/2023 12:00:00 AM
13576995    12/31/2023 12:00:00 AM
13576996    12/31/2023 12:00:00 AM
13576997    12/31/2023 12:00:00 AM
13576998    12/31/2023 12:00:00 AM
13576999    12/31/2023 12:00:00 AM
13577000    12/31/2023 12:00:00 AM
13577001    12/31/2023 12:00:00 AM
13577002    12/31/2023 12:00:00 AM
13577003    12/31/2023 12:00:00 AM
13577004    12/31/2023 12:00:00 AM
13577005    12/31/2023 12:00:00 AM
13577006    12/31/2023 12:00:00 AM
13577007    12/31/2023 12:00:00 AM
13577008    12/31/2023 12:00:00 AM
13577009    12/31/2023 12:00:00 AM
13577010    12/31/2023 12:00:00 AM
13577011    12/31/2023 12:00:00 AM
13577012    12/31/2023 12:00:00 AM
13577013    12/31/2023 12:00:00 AM
13577014    12/31/2023 12:00:00 AM
13577015    12/31/2023 12:00:00 AM
13577016    12/31/2023 12:00:00 AM
13577017    12/31/2023 12:00:00 AM
13577018    12/31/2023 12:00:00 AM
13577019    12/31/2023 12:00:00 AM
13577020    12/31/2023 12:00:00 AM
13577021    12/31/2023 12:00:00 AM
13577022    12/31/2023 12:00:00 AM
13577023    12/31/2023 12:00:00 AM
Name: FL_DATE, dtype: object

In [22]:
df['OP_UNIQUE_CARRIER'].value_counts()

OP_UNIQUE_CARRIER
WN    2745614
DL    1878158
AA    1814676
OO    1408739
UA    1358685
YX     611799
B6     547910
NK     496271
MQ     475547
AS     473728
9E     433461
OH     408594
F9     333024
G4     232416
HA     154832
YV     114779
QX      88791
Name: count, dtype: int64

In [26]:
len(df['ORIGIN_AIRPORT_ID'].unique())

372

In [28]:
len(df['ORIGIN_AIRPORT_SEQ_ID'].unique())

428

In [29]:
len(df['ORIGIN_CITY_MARKET_ID'].unique())

348

In [30]:
df['ORIGIN_CITY_NAME'].value_counts()

ORIGIN_CITY_NAME
Chicago, IL              681402
Atlanta, GA              654389
New York, NY             602771
Dallas/Fort Worth, TX    561952
Denver, CO               560452
                          ...
Wilmington, DE               47
Branson, MO                  47
Ogden, UT                    29
Pierre, SD                    3
Watertown, SD                 2
Name: count, Length: 366, dtype: int64

In [31]:
len(df['DEST_AIRPORT_ID'].unique())

373

In [32]:
len(df['DEST_AIRPORT_SEQ_ID'].unique())

429

In [33]:
len(df['DEST_CITY_MARKET_ID'].unique())

349

In [34]:
df['ORIGIN_CITY_MARKET_ID'].unique()

array([30135, 30146, 30185, 30208, 30257, 30397, 30408, 30431, 30469,
       30577, 30599, 30627, 30685, 30693, 30721, 30731, 30781, 30785,
       30792, 30868, 30980, 30990, 30994, 31003, 30647, 31066, 31146,
       31150, 33105, 30424, 31267, 30194, 31308, 31337, 31423, 31295,
       31612, 31703, 31624, 31775, 31823, 31898, 31953, 31973, 31977,
       31995, 31871, 30894, 30928, 32323, 32337, 32397, 32448, 32884,
       32945, 32951, 33184, 32070, 30977, 33244, 33277, 33342, 33367,
       33377, 30562, 33304, 33485, 31650, 33795, 33667, 34100, 34321,
       34492, 34524, 34574, 34576, 32547, 34685, 34696, 34711, 33044,
       34783, 30476, 31123, 35096, 35249, 35323, 34653, 35380, 35412,
       35550, 31504, 31834, 30140, 30423, 30529, 32575, 30852, 30849,
       31057, 30325, 31503, 30615, 31603, 31638, 32467, 31884, 31986,
       32012, 34699, 32134, 31453, 32441, 31136, 32758, 32211, 32982,
       33198, 31454, 33256, 33486, 33495, 33502, 33830, 33851, 33316,
       34027, 34057, 30466, 30198, 33728, 34262, 34570, 31714, 33570,
       33214, 34689, 30559, 32457, 34819, 34614, 33192, 34986, 34945,
       34992, 33195, 30436, 30165, 30070, 30299, 30113, 30713, 30107,
       31517, 32523, 31401, 33970, 34828, 30732, 33933, 34254, 30620,
       31252, 31481, 31637, 31641, 31648, 30255, 32600, 33360, 31135,
       30189, 32206, 35356, 30666, 30676, 31721, 32223, 32280, 32544,
       34025, 34082, 34108, 34259, 34314, 34457, 34512, 34716, 34761,
       34952, 32556, 35165, 32402, 30136, 30155, 30268, 30728, 30747,
       31049, 31067, 32474, 31140, 31274, 31335, 31778, 31867, 31905,
       31980, 31982, 32891, 32896, 31205, 33038, 33076, 33158, 33290,
       33459, 34922, 34236, 34842, 34960, 35074, 35401, 35411, 30158,
       32898, 30434, 30581, 31577, 31617, 30141, 30157, 30272, 30279,
       30333, 30372, 30558, 30561, 30617, 30631, 30739, 30779, 30918,
       30967, 31013, 31027, 31076, 31092, 31097, 31122, 31233, 31283,
       31288, 30285, 31447, 31468, 31471, 31525, 31537, 31587, 31695,
       31725, 31865, 31921, 31895, 32129, 32156, 32177, 32255, 32335,
       32343, 32511, 32519, 32559, 32888, 32899, 32902, 33029, 33121,
       33127, 33211, 33241, 33264, 33344, 33832, 34006, 34109, 34113,
       34150, 34237, 34252, 34288, 33792, 34489, 34520, 34534, 34543,
       34588, 34674, 34794, 34802, 34812, 34877, 34433, 35041, 35048,
       35138, 35389, 35569, 35582, 33785, 32389, 30275, 31470, 34004,
       34303, 36101, 32016, 34955, 32124, 30913, 33873, 34256, 35841,
       35991, 32119, 32265, 34905, 30409, 33964, 34120, 30245, 31336,
       30073, 32320, 32131, 33139, 34222, 33983, 31315, 30154, 35897,
       30643, 31997, 32250, 33541, 31699, 34092], dtype=int64)

In [36]:
len(df['DEST_CITY_NAME'].unique())

367

In [37]:
df['CRS_DEP_TIME'].max()

2359

In [38]:
df['CRS_DEP_TIME'].min()

1

In [39]:
df['DEP_TIME'].head()

0     631.0
1    1014.0
2       NaN
3     712.0
4    1416.0
Name: DEP_TIME, dtype: float64

In [41]:
df['DEP_TIME'].max()

2400.0

In [42]:
df['DEP_TIME'].min()

1.0

In [43]:
df['DEP_DELAY'              ].max()

4413.0

In [44]:
df['DEP_DELAY'              ].min()

-99.0

In [48]:
df['DEP_DELAY_NEW'].value_counts()

DEP_DELAY_NEW
0.0       8179720
1.0        304217
2.0        252360
3.0        225313
4.0        204756
           ...
1705.0          1
2036.0          1
1790.0          1
1778.0          1
1611.0          1
Name: count, Length: 1949, dtype: int64

In [49]:
df['DEP_DELAY_NEW'].min()

0.0

In [50]:
df['DEP_DELAY_NEW'].max()

4413.0

In [51]:
df['DEP_DEL15'].value_counts()

DEP_DEL15
0.0    10528467
1.0     2786680
Name: count, dtype: int64

In [55]:
df['DEP_DELAY_GROUP'].value_counts()

DEP_DELAY_GROUP
-1.0     7484331
 0.0     2987599
 1.0      997192
 2.0      528850
 3.0      325376
 4.0      217479
 12.0     172787
 5.0      153845
 6.0      114215
 7.0       86971
 8.0       65773
-2.0       56537
 9.0       51059
 10.0      40777
 11.0      32356
Name: count, dtype: int64

In [57]:
df['CRS_ARR_TIME'].min()

1

In [56]:
df['CRS_ARR_TIME'].max()

2400

In [58]:
df['ARR_TIME'].min()

1.0

In [59]:
df['ARR_TIME'].max()

2400.0

In [60]:
df['ARR_DELAY'].min()

-119.0

In [61]:
df['ARR_DELAY'].max()

4405.0

In [64]:
df['ARR_DELAY_NEW'].min()

0.0

In [65]:
df['ARR_DELAY_NEW'].max()

4405.0

In [66]:
df['ARR_DEL15'].value_counts()

ARR_DEL15
0.0    10511918
1.0     2763497
Name: count, dtype: int64

In [67]:
df['CANCELLED'].value_counts()

CANCELLED
0.0    13307795
1.0      269229
Name: count, dtype: int64

In [68]:
df['DIVERTED'].value_counts()

DIVERTED
0.0    13544646
1.0       32378
Name: count, dtype: int64

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13577024 entries, 0 to 13577023
Data columns (total 28 columns):
 #   Column                 Dtype
---  ------                 -----
 0   YEAR                   int64
 1   QUARTER                int64
 2   MONTH                  int64
 3   DAY_OF_MONTH           int64
 4   DAY_OF_WEEK            int64
 5   FL_DATE                object
 6   OP_UNIQUE_CARRIER      object
 7   ORIGIN_AIRPORT_ID      int64
 8   ORIGIN_AIRPORT_SEQ_ID  int64
 9   ORIGIN_CITY_MARKET_ID  int64
 10  ORIGIN_CITY_NAME       object
 11  DEST_AIRPORT_ID        int64
 12  DEST_AIRPORT_SEQ_ID    int64
 13  DEST_CITY_MARKET_ID    int64
 14  DEST_CITY_NAME         object
 15  CRS_DEP_TIME           int64
 16  DEP_TIME               float64
 17  DEP_DELAY              float64
 18  DEP_DELAY_NEW          float64
 19  DEP_DEL15              float64
 20  DEP_DELAY_GROUP        float64
 21  CRS_ARR_TIME           int64
 22  ARR_TIME               float64
 23  ARR_DELAY              float64
 24  ARR_DELAY_NEW          float64
 25  ARR_DEL15              float64
 26  CANCELLED              float64
 27  DIVERTED               float64
dtypes: float64(11), int64(13), object(4)
memory usage: 2.8+ GB

In [23]:
df.columns

Index(['YEAR', 'QUARTER', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'FL_DATE',
       'OP_UNIQUE_CARRIER', 'ORIGIN_AIRPORT_ID', 'ORIGIN_AIRPORT_SEQ_ID',
       'ORIGIN_CITY_MARKET_ID', 'ORIGIN_CITY_NAME', 'DEST_AIRPORT_ID',
       'DEST_AIRPORT_SEQ_ID', 'DEST_CITY_MARKET_ID', 'DEST_CITY_NAME',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'DEP_DELAY_NEW', 'DEP_DEL15',
       'DEP_DELAY_GROUP', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'ARR_DELAY_NEW', 'ARR_DEL15', 'CANCELLED', 'DIVERTED'],
      dtype='object')

In [46]:
df.isnull().sum().sort_values(ascending=False)

ARR_DEL15                301609
ARR_DELAY_NEW            301609
ARR_DELAY                301609
ARR_TIME                 272574
DEP_DELAY_GROUP          261877
DEP_DEL15                261877
DEP_DELAY_NEW            261877
DEP_DELAY                261877
DEP_TIME                 261738
YEAR                          0
QUARTER                       0
CANCELLED                     0
CRS_ARR_TIME                  0
CRS_DEP_TIME                  0
DEST_CITY_NAME                0
DEST_CITY_MARKET_ID           0
DEST_AIRPORT_SEQ_ID           0
DEST_AIRPORT_ID               0
ORIGIN_CITY_NAME              0
ORIGIN_CITY_MARKET_ID         0
ORIGIN_AIRPORT_SEQ_ID         0
ORIGIN_AIRPORT_ID             0
OP_UNIQUE_CARRIER             0
FL_DATE                       0
DAY_OF_WEEK                   0
DAY_OF_MONTH                  0
MONTH                         0
DIVERTED                      0
dtype: int64

### Análise dos valores nulos

In [9]:
masc = (df["ARR_DEL15"].isnull()) & (df["ARR_DELAY_NEW"].isnull()) & (df["ARR_DELAY"].isnull())
sum(masc)

301609

In [10]:
df[df["ARR_DELAY"].isnull()]['DIVERTED'].value_counts()

DIVERTED
0.0    269231
1.0     32378
Name: count, dtype: int64

In [11]:
df[df["ARR_DELAY"].isnull()]['CANCELLED'].value_counts()

CANCELLED
1.0    269229
0.0     32380
Name: count, dtype: int64

*Valores nulos nas arrivals justificam-se pelo voo ser cancelado ou divergido à exceção de 2 ocasiões*

In [12]:
subset = df[df["ARR_DELAY"].isnull()]
mask = (subset["CANCELLED"] == 1) | (subset["DIVERTED"] == 1)
sum(mask)

301607

In [13]:
maskII = (subset["CANCELLED"] == 0) & (subset["DIVERTED"] == 0)
subset.loc[maskII,:]

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,...,DEP_DELAY_NEW,DEP_DEL15,DEP_DELAY_GROUP,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,CANCELLED,DIVERTED
6542772,2022,4,12,21,3,12/21/2022 12:00:00 AM,F9,11292,1129202,30325,...,0.0,0.0,-1.0,2100,NaN,NaN,NaN,NaN,0.0,0.0
9305191,2023,2,5,21,7,5/21/2023 12:00:00 AM,YX,12953,1295304,31703,...,37.0,1.0,2.0,1746,NaN,NaN,NaN,NaN,0.0,0.0

*Razão de haver nulos em valores de departure como dep_delay: voo cancelado*

DEP_DEL15	261877

In [14]:
df[df["DEP_DELAY"].isnull()]['CANCELLED'].value_counts()

CANCELLED
1.0    261877
Name: count, dtype: int64